coverage:
  status:
    project:
      default: off
      ixnet:
        flags: ixnet
      rxnet:
        flags: rxnet

flags:
  ixnet:
    paths: Ix.NET/Source/
  rxnet:
    paths: Rx.NET/Source/src/

codecov:
  ci:
    - dev.azure.com